name: GitHub-Profile-Atcorder
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-atcorder
    steps:
      - uses: actions/checkout@v3
      - uses: kinakomoch7/git-hub-profile-atcorder@0.0.1
        env:
          USERNAME: kinako_moch7
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
