name: GitHub-Profile-Atcorder
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-atcorder
    steps:
      - uses: actions/checkout@v3
      - uses: kinakomoch7/git-hub-profile-atcorder@v0.1.4
        env:
          USER_NAME: kinako_moch7
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
